# Generated by Django 5.2.11 on 2026-02-23 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('conge', 'Congé'), ('retard', 'Retard'), ('permission', 'Permission'), ('repos_medical', 'Repos médical'), ('ostie', 'OSTIE'), ('ferie', 'Jour férié'), ('exceptionnel', 'Jour exceptionnel'), ('weekend', 'Weekend'), ('system', 'Système')], db_index=True, max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, help_text='Code couleur hexadécimal', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_blocked', models.BooleanField(default=False, help_text='Jour bloqué (pas de congés)')),
                ('is_system', models.BooleanField(default=False, help_text='Événement système')),
                ('statut', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_date', 'start_time'],
                'indexes': [models.Index(fields=['event_type', 'start_date'], name='events_even_event_t_25d715_idx'), models.Index(fields=['user', 'start_date'], name='events_even_user_id_013578_idx'), models.Index(fields=['is_system'], name='events_even_is_syst_9301bd_idx')],
            },
        ),
    ]
