# Generated by Django 5.2.11 on 2026-02-19 11:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conges', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la permission')),
                ('heure_depart', models.TimeField(verbose_name='Heure de départ')),
                ('heure_arrivee_max', models.TimeField(help_text='Calculé automatiquement: heure_depart + 2h', verbose_name="Heure d'arrivée max")),
                ('heure_arrivee_reelle', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée réelle")),
                ('motif', models.TextField(verbose_name='Motif de la permission')),
                ('minutes_depassement', models.PositiveIntegerField(default=0, editable=False, verbose_name='Minutes de dépassement')),
                ('heures_a_rattraper', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Heures à rattraper')),
                ('heures_restantes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Heures restantes à rattraper')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('retourne', 'Retourné'), ('rattrapage', 'Rattrapage en cours'), ('approuve', 'Approuvé'), ('transforme', 'Transformé en congé'), ('annule', 'Annulé')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('rattrapages', models.JSONField(blank=True, default=list, verbose_name='Sessions de rattrapage')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_annulation', models.TextField(blank=True, null=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('conge_genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_origine', to='conges.conge', verbose_name='Congé généré')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['-date', '-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'date'], name='permissions_utilisa_6cf303_idx'), models.Index(fields=['statut'], name='permissions_statut_6a1dd8_idx')],
            },
        ),
    ]
