# Generated by Django 5.2.11 on 2026-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rattrapage_forfaitaire_minutes', models.PositiveIntegerField(default=30, help_text='Minutes de rattrapage obligatoire même en cas de retour dans les temps', verbose_name='Rattrapage forfaitaire (minutes)')),
            ],
            options={
                'verbose_name': 'Configuration des permissions',
                'verbose_name_plural': 'Configurations des permissions',
            },
        ),
    ]
