# Generated by Django 5.2.11 on 2026-02-18 13:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rattrapage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rattrapage', models.DateField(verbose_name='Date du rattrapage')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('heures_rattrapees', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Heures rattrapées')),
                ('date_validation', models.DateTimeField(auto_now_add=True, verbose_name='Date de validation')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Rattrapage',
                'verbose_name_plural': 'Rattrapages',
                'ordering': ['-date_rattrapage'],
            },
        ),
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du retard')),
                ('heure_debut_prevue', models.TimeField(verbose_name='Heure de début prévue')),
                ('heure_arrivee_reelle', models.TimeField(verbose_name="Heure d'arrivée réelle")),
                ('minutes_retard', models.PositiveIntegerField(default=0, editable=False, verbose_name='Minutes de retard')),
                ('heures_a_rattraper', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Heures à rattraper')),
                ('heures_restantes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Heures restantes à rattraper')),
                ('motif_retard', models.TextField(blank=True, null=True, verbose_name='Justificatif / Motif du retard')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de rattrapage'), ('en_cours', 'Rattrapage en cours'), ('approuve', 'Rattrapé / Approuvé'), ('annule', 'Annulé'), ('remplace', 'Remplacé')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('commentaire_annulation', models.TextField(blank=True, null=True, verbose_name="Commentaire d'annulation")),
            ],
            options={
                'verbose_name': 'Retard',
                'verbose_name_plural': 'Retards',
                'ordering': ['-date', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TypeRetardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Retard léger, Retard matinal, etc.', max_length=50, unique=True, verbose_name='Nom du type de retard')),
                ('heure_debut_prevue', models.TimeField(default='08:00', help_text="Heure à laquelle l'utilisateur est censé commencer", verbose_name='Heure de début prévue')),
                ('minutes_min', models.PositiveIntegerField(help_text='Seuil minimum inclus', verbose_name='Minutes minimum')),
                ('minutes_max', models.PositiveIntegerField(blank=True, help_text='Seuil maximum inclus (null = illimité)', null=True, verbose_name='Minutes maximum')),
                ('multiplicateur', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='Multiplicateur de rattrapage')),
                ('couleur', models.CharField(default='#ff9800', max_length=7, verbose_name='Couleur dans le calendrier')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Configuration type de retard',
                'verbose_name_plural': 'Configurations types de retard',
                'ordering': ['ordre', 'minutes_min'],
            },
        ),
    ]
