# Generated by Django 5.2.11 on 2026-02-18 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rattrapage',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rattrapages_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='retard',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='retard',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='retard',
            name='retard_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards_fractionnes', to='retards.retard', verbose_name='Retard original'),
        ),
        migrations.AddField(
            model_name='retard',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='rattrapage',
            name='retard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rattrapages', to='retards.retard', verbose_name='Retard concerné'),
        ),
        migrations.AddField(
            model_name='retard',
            name='type_retard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retards', to='retards.typeretardconfig', verbose_name='Type de retard'),
        ),
        migrations.AddIndex(
            model_name='retard',
            index=models.Index(fields=['utilisateur', 'date'], name='retards_ret_utilisa_fad067_idx'),
        ),
        migrations.AddIndex(
            model_name='retard',
            index=models.Index(fields=['statut'], name='retards_ret_statut_e1640a_idx'),
        ),
    ]
