# Generated by Django 5.2.11 on 2026-02-23 08:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conges', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReposMedicalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_max_par_an', models.PositiveIntegerField(default=30, help_text='Nombre maximum de jours de repos médical par an', verbose_name='Jours max par an')),
            ],
            options={
                'verbose_name': 'Configuration des repos médicaux',
                'verbose_name_plural': 'Configurations des repos médicaux',
            },
        ),
        migrations.CreateModel(
            name='ReposMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du repos')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('duree_heures', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Durée en heures')),
                ('motif', models.TextField(blank=True, default='Malade', verbose_name='Motif')),
                ('avertissement', models.TextField(default="N'oublie pas d'apporter ton justificatif médical (PJ)", help_text="Message affiché à l'utilisateur", verbose_name='Avertissement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('transforme', 'Transformé en congé'), ('annule', 'Annulé')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_annulation', models.TextField(blank=True, null=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repos_medicaux_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('conge_genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repos_medical_origine', to='conges.conge', verbose_name='Congé généré')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos_medicaux', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repos_medicaux_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Repos médical',
                'verbose_name_plural': 'Repos médicaux',
                'ordering': ['-date', '-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'date'], name='reposmedica_utilisa_759fdd_idx'), models.Index(fields=['statut'], name='reposmedica_statut_8dfcb8_idx')],
            },
        ),
    ]
