# Generated by Django 5.2.11 on 2026-02-23 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reposmedicale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OstieConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Configuration des OSTIES',
                'verbose_name_plural': 'Configurations des OSTIES',
            },
        ),
        migrations.CreateModel(
            name='Ostie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date de l'OSTIE")),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('transforme', 'Transformé en Repos Médical'), ('annule', 'Annulé')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_annulation', models.TextField(blank=True, null=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osties_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('repos_genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ostie_origine', to='reposmedicale.reposmedical', verbose_name='Repos médical généré')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osties', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osties_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'OSTIE',
                'verbose_name_plural': 'OSTIES',
                'ordering': ['-date', '-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'date'], name='ostie_ostie_utilisa_b05ded_idx'), models.Index(fields=['statut'], name='ostie_ostie_statut_087a3f_idx')],
            },
        ),
    ]
