# Generated by Django 5.2.11 on 2026-02-18 13:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongeAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Congé annuel',
                'verbose_name_plural': 'Congés annuels',
                'ordering': ['-annee', 'date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du droit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Droit (congé exceptionnel)',
                'verbose_name_plural': 'Droits (congés exceptionnels)',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='JourExceptionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_jour', models.CharField(choices=[('exceptionnel', 'Jour exceptionnel (rayé)'), ('non_exceptionnel', 'Jour non-exceptionnel (dé-rayé)')], max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Jour exceptionnel',
                'verbose_name_plural': 'Jours exceptionnels',
                'ordering': ['-annee', 'date'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('jour', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['mois', 'jour'],
            },
        ),
        migrations.CreateModel(
            name='TypeCongeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('matin', 'Matin'), ('midi', 'Midi'), ('journee', 'Une journée')], max_length=20, unique=True, verbose_name='Type de congé')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('deduction_jours', models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Nombre de jours déduits du solde', max_digits=3, verbose_name='Déduction (jours)')),
                ('vendredi_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Si différent du standard (ex: Vendredi Midi = 2.5)', max_digits=3, null=True, verbose_name='Déduction Vendredi')),
                ('jeudi_deduction', models.DecimalField(blank=True, decimal_places=2, help_text='Si Vendredi est rayé, Jeudi = -3 jours', max_digits=3, null=True, verbose_name='Déduction Jeudi')),
            ],
            options={
                'verbose_name': 'Configuration type de congé',
                'verbose_name_plural': 'Configurations types de congé',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('matin', 'Matin'), ('midi', 'Midi'), ('journee', 'Une journée')], max_length=20, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('jours_deduits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculé automatiquement selon les règles', max_digits=5, verbose_name='Jours déduits')),
                ('jours_valides', models.JSONField(blank=True, default=list, help_text='Liste des dates validées (pour validation partielle)', verbose_name='Jours validés')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_refus', models.DateTimeField(blank=True, null=True, verbose_name='Date de refus')),
                ('commentaire_refus', models.TextField(blank=True, null=True, verbose_name='Commentaire de refus')),
                ('est_droit', models.BooleanField(default=False, verbose_name='Est un droit (congé exceptionnel)')),
                ('conge_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_fractionnes', to='conges.conge', verbose_name='Congé original')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_debut'],
            },
        ),
    ]
