# Generated by Django 5.2.11 on 2026-02-18 13:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('last_run', models.DateTimeField()),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de job planifié',
                'verbose_name_plural': 'Logs de jobs planifiés',
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du pôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pôle',
                'verbose_name_plural': 'Pôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('pseudo', models.CharField(blank=True, help_text='Pseudonyme personnalisé', max_length=100, null=True, verbose_name='Pseudo')),
                ('pseudo_format', models.CharField(choices=[('first_word', 'Premier mot du nom'), ('second_word', 'Deuxième mot du nom'), ('third_word', 'Troisième mot du nom'), ('first_two', 'Premier + Deuxième mots'), ('last_two', 'Deuxième + Troisième mots'), ('all_words', 'Tous les mots'), ('custom', 'Personnalisé (saisie libre)')], default='first_word', help_text='Comment générer le pseudo à partir du nom', max_length=20, verbose_name='Format du pseudo')),
                ('solde_conge_recue_par_mois', models.DecimalField(decimal_places=2, default=2.5, help_text='Nombre de jours de congé ajoutés chaque mois (défaut: 2.5)', max_digits=4, verbose_name='Solde congé reçu par mois')),
                ('solde_conge_actuelle', models.DecimalField(decimal_places=2, default=0.0, help_text='Solde disponible actuellement', max_digits=5, verbose_name='Solde congé actuel')),
                ('solde_conge_consomme', models.DecimalField(decimal_places=2, default=0.0, help_text='Total des congés pris', max_digits=5, verbose_name='Solde congé consommé')),
                ('motif_conge', models.TextField(blank=True, help_text='Raison de la demande de congé', null=True, verbose_name='Motif du dernier congé')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('keycloak_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Keycloak')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'équipe")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('co_managers', models.ManyToManyField(blank=True, related_name='equipes_co_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Co-managers')),
                ('equipe_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_equipes', to='users.equipe', verbose_name='Équipe parente')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_gerees', to=settings.AUTH_USER_MODEL, verbose_name="Manager/Chef d'équipe")),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='users.pole', verbose_name='Pôle')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='users.equipe', verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='users.pole', verbose_name='Pôle'),
        ),
    ]
